// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type CreateSlackEmojiActionRequestBody struct {
	// The name of the emoji to associate with this action
	EmojiName string `json:"emoji_name"`
	// The ID of the incident type to associate with this emoji action
	IncidentTypeID *string `json:"incident_type_id,omitempty"`
}

func (o *CreateSlackEmojiActionRequestBody) GetEmojiName() string {
	if o == nil {
		return ""
	}
	return o.EmojiName
}

func (o *CreateSlackEmojiActionRequestBody) GetIncidentTypeID() *string {
	if o == nil {
		return nil
	}
	return o.IncidentTypeID
}

type CreateSlackEmojiActionRequest struct {
	// Slack Connection UUID
	ConnectionID string                            `pathParam:"style=simple,explode=false,name=connection_id"`
	RequestBody  CreateSlackEmojiActionRequestBody `request:"mediaType=application/json"`
}

func (o *CreateSlackEmojiActionRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *CreateSlackEmojiActionRequest) GetRequestBody() CreateSlackEmojiActionRequestBody {
	if o == nil {
		return CreateSlackEmojiActionRequestBody{}
	}
	return o.RequestBody
}

type CreateSlackEmojiActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A collection of codes that generally means the end user got something wrong in making the request
	BadRequest *shared.BadRequest
	// A collection of codes that generally means the client was not authenticated correctly for the request they want to make
	Unauthorized *shared.Unauthorized
	// Status codes relating to the resource/entity they are requesting not being found or endpoints/routes not existing
	NotFound *shared.NotFound
	// Status codes relating to the client being rate limited by the server
	RateLimited *shared.RateLimited
	// A collection of status codes that generally mean the server failed in an unexpected way
	InternalServerError *shared.InternalServerError
	// Timeouts occurred with the request
	Timeout *shared.Timeout
}

func (o *CreateSlackEmojiActionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateSlackEmojiActionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateSlackEmojiActionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateSlackEmojiActionResponse) GetBadRequest() *shared.BadRequest {
	if o == nil {
		return nil
	}
	return o.BadRequest
}

func (o *CreateSlackEmojiActionResponse) GetUnauthorized() *shared.Unauthorized {
	if o == nil {
		return nil
	}
	return o.Unauthorized
}

func (o *CreateSlackEmojiActionResponse) GetNotFound() *shared.NotFound {
	if o == nil {
		return nil
	}
	return o.NotFound
}

func (o *CreateSlackEmojiActionResponse) GetRateLimited() *shared.RateLimited {
	if o == nil {
		return nil
	}
	return o.RateLimited
}

func (o *CreateSlackEmojiActionResponse) GetInternalServerError() *shared.InternalServerError {
	if o == nil {
		return nil
	}
	return o.InternalServerError
}

func (o *CreateSlackEmojiActionResponse) GetTimeout() *shared.Timeout {
	if o == nil {
		return nil
	}
	return o.Timeout
}
