// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type CreateServiceChecklistResponseRequest struct {
	ServiceID                      string                                `pathParam:"style=simple,explode=false,name=service_id"`
	ChecklistID                    string                                `pathParam:"style=simple,explode=false,name=checklist_id"`
	CreateServiceChecklistResponse shared.CreateServiceChecklistResponse `request:"mediaType=application/json"`
}

func (o *CreateServiceChecklistResponseRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *CreateServiceChecklistResponseRequest) GetChecklistID() string {
	if o == nil {
		return ""
	}
	return o.ChecklistID
}

func (o *CreateServiceChecklistResponseRequest) GetCreateServiceChecklistResponse() shared.CreateServiceChecklistResponse {
	if o == nil {
		return shared.CreateServiceChecklistResponse{}
	}
	return o.CreateServiceChecklistResponse
}

type CreateServiceChecklistResponseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateServiceChecklistResponseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateServiceChecklistResponseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateServiceChecklistResponseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
