// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type CreateServiceChecklistResponseRequest struct {
	ServiceID                                           string                                                     `pathParam:"style=simple,explode=false,name=service_id"`
	ChecklistID                                         string                                                     `pathParam:"style=simple,explode=false,name=checklist_id"`
	PostV1ServicesServiceIDChecklistResponseChecklistID shared.PostV1ServicesServiceIDChecklistResponseChecklistID `request:"mediaType=application/json"`
}

func (o *CreateServiceChecklistResponseRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *CreateServiceChecklistResponseRequest) GetChecklistID() string {
	if o == nil {
		return ""
	}
	return o.ChecklistID
}

func (o *CreateServiceChecklistResponseRequest) GetPostV1ServicesServiceIDChecklistResponseChecklistID() shared.PostV1ServicesServiceIDChecklistResponseChecklistID {
	if o == nil {
		return shared.PostV1ServicesServiceIDChecklistResponseChecklistID{}
	}
	return o.PostV1ServicesServiceIDChecklistResponseChecklistID
}

type CreateServiceChecklistResponseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A collection of codes that generally means the end user got something wrong in making the request
	BadRequest *shared.BadRequest
	// A collection of codes that generally means the client was not authenticated correctly for the request they want to make
	Unauthorized *shared.Unauthorized
	// Status codes relating to the resource/entity they are requesting not being found or endpoints/routes not existing
	NotFound *shared.NotFound
	// Status codes relating to the client being rate limited by the server
	RateLimited *shared.RateLimited
	// A collection of status codes that generally mean the server failed in an unexpected way
	InternalServerError *shared.InternalServerError
	// Timeouts occurred with the request
	Timeout *shared.Timeout
}

func (o *CreateServiceChecklistResponseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateServiceChecklistResponseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateServiceChecklistResponseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateServiceChecklistResponseResponse) GetBadRequest() *shared.BadRequest {
	if o == nil {
		return nil
	}
	return o.BadRequest
}

func (o *CreateServiceChecklistResponseResponse) GetUnauthorized() *shared.Unauthorized {
	if o == nil {
		return nil
	}
	return o.Unauthorized
}

func (o *CreateServiceChecklistResponseResponse) GetNotFound() *shared.NotFound {
	if o == nil {
		return nil
	}
	return o.NotFound
}

func (o *CreateServiceChecklistResponseResponse) GetRateLimited() *shared.RateLimited {
	if o == nil {
		return nil
	}
	return o.RateLimited
}

func (o *CreateServiceChecklistResponseResponse) GetInternalServerError() *shared.InternalServerError {
	if o == nil {
		return nil
	}
	return o.InternalServerError
}

func (o *CreateServiceChecklistResponseResponse) GetTimeout() *shared.Timeout {
	if o == nil {
		return nil
	}
	return o.Timeout
}
