// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1IncidentsIncidentIDTranscriptTranscriptIDRequest struct {
	TranscriptID string `pathParam:"style=simple,explode=false,name=transcript_id"`
	IncidentID   string `pathParam:"style=simple,explode=false,name=incident_id"`
}

func (o *DeleteV1IncidentsIncidentIDTranscriptTranscriptIDRequest) GetTranscriptID() string {
	if o == nil {
		return ""
	}
	return o.TranscriptID
}

func (o *DeleteV1IncidentsIncidentIDTranscriptTranscriptIDRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

type DeleteV1IncidentsIncidentIDTranscriptTranscriptIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteV1IncidentsIncidentIDTranscriptTranscriptIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteV1IncidentsIncidentIDTranscriptTranscriptIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteV1IncidentsIncidentIDTranscriptTranscriptIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
