// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteIncidentTeamAssignmentRequestBody struct {
	// Team role assignments to unassign from the incident
	RoleAssignmentIds []string `multipartForm:"name=role_assignment_ids"`
}

func (o *DeleteIncidentTeamAssignmentRequestBody) GetRoleAssignmentIds() []string {
	if o == nil {
		return nil
	}
	return o.RoleAssignmentIds
}

type DeleteIncidentTeamAssignmentRequest struct {
	IncidentID       string                                   `pathParam:"style=simple,explode=false,name=incident_id"`
	TeamAssignmentID string                                   `pathParam:"style=simple,explode=false,name=team_assignment_id"`
	RequestBody      *DeleteIncidentTeamAssignmentRequestBody `request:"mediaType=multipart/form-data"`
}

func (o *DeleteIncidentTeamAssignmentRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *DeleteIncidentTeamAssignmentRequest) GetTeamAssignmentID() string {
	if o == nil {
		return ""
	}
	return o.TeamAssignmentID
}

func (o *DeleteIncidentTeamAssignmentRequest) GetRequestBody() *DeleteIncidentTeamAssignmentRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type DeleteIncidentTeamAssignmentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteIncidentTeamAssignmentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteIncidentTeamAssignmentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteIncidentTeamAssignmentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
