// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type ExportIncidentRetrospectivesRequestBody struct {
	// The name of the integration to export the retrospective to.
	IntegrationSlug string `json:"integration_slug"`
	// The ID of the parent page to export the retrospective to.
	ParentPageID *string `json:"parent_page_id,omitempty"`
}

func (o *ExportIncidentRetrospectivesRequestBody) GetIntegrationSlug() string {
	if o == nil {
		return ""
	}
	return o.IntegrationSlug
}

func (o *ExportIncidentRetrospectivesRequestBody) GetParentPageID() *string {
	if o == nil {
		return nil
	}
	return o.ParentPageID
}

type ExportIncidentRetrospectivesRequest struct {
	IncidentID  string                                  `pathParam:"style=simple,explode=false,name=incident_id"`
	RequestBody ExportIncidentRetrospectivesRequestBody `request:"mediaType=application/json"`
}

func (o *ExportIncidentRetrospectivesRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *ExportIncidentRetrospectivesRequest) GetRequestBody() ExportIncidentRetrospectivesRequestBody {
	if o == nil {
		return ExportIncidentRetrospectivesRequestBody{}
	}
	return o.RequestBody
}

type ExportIncidentRetrospectivesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Export incident's retrospective(s) using their templates
	IncidentsExportRetrospectivesResultEntity *shared.IncidentsExportRetrospectivesResultEntity
}

func (o *ExportIncidentRetrospectivesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ExportIncidentRetrospectivesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ExportIncidentRetrospectivesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ExportIncidentRetrospectivesResponse) GetIncidentsExportRetrospectivesResultEntity() *shared.IncidentsExportRetrospectivesResultEntity {
	if o == nil {
		return nil
	}
	return o.IncidentsExportRetrospectivesResultEntity
}
