// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type GetV1EnvironmentsEnvironmentIDRequest struct {
	// Environment UUID
	EnvironmentID string `pathParam:"style=simple,explode=false,name=environment_id"`
}

func (o *GetV1EnvironmentsEnvironmentIDRequest) GetEnvironmentID() string {
	if o == nil {
		return ""
	}
	return o.EnvironmentID
}

type GetV1EnvironmentsEnvironmentIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Retrieves a single environment by ID
	EnvironmentEntryEntity *shared.EnvironmentEntryEntity
}

func (o *GetV1EnvironmentsEnvironmentIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetV1EnvironmentsEnvironmentIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetV1EnvironmentsEnvironmentIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetV1EnvironmentsEnvironmentIDResponse) GetEnvironmentEntryEntity() *shared.EnvironmentEntryEntity {
	if o == nil {
		return nil
	}
	return o.EnvironmentEntryEntity
}
