// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type ListFunctionalitiesRequest struct {
	// A query to search functionalities by their name or description
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// A query to search functionalities by their name
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// A query to search services by if they are impacted with active incidents
	Impacted *string `queryParam:"style=form,explode=true,name=impacted"`
	// A comma separated list of label key / values in the format of 'key=value,key2=value2'. To filter change events that have a key (with no specific value), omit the value
	Labels *string `queryParam:"style=form,explode=true,name=labels"`
	// A query to search functionalities by their owning team ID
	Owner *string `queryParam:"style=form,explode=true,name=owner"`
	// Boolean to determine whether to return a slimified version of the functionalities object
	Lite    *bool `queryParam:"style=form,explode=true,name=lite"`
	Page    *int  `queryParam:"style=form,explode=true,name=page"`
	PerPage *int  `queryParam:"style=form,explode=true,name=per_page"`
}

func (o *ListFunctionalitiesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListFunctionalitiesRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ListFunctionalitiesRequest) GetImpacted() *string {
	if o == nil {
		return nil
	}
	return o.Impacted
}

func (o *ListFunctionalitiesRequest) GetLabels() *string {
	if o == nil {
		return nil
	}
	return o.Labels
}

func (o *ListFunctionalitiesRequest) GetOwner() *string {
	if o == nil {
		return nil
	}
	return o.Owner
}

func (o *ListFunctionalitiesRequest) GetLite() *bool {
	if o == nil {
		return nil
	}
	return o.Lite
}

func (o *ListFunctionalitiesRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListFunctionalitiesRequest) GetPerPage() *int {
	if o == nil {
		return nil
	}
	return o.PerPage
}

type ListFunctionalitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List all of the functionalities that have been added to the organiation
	FunctionalityEntityPaginated *shared.FunctionalityEntityPaginated
}

func (o *ListFunctionalitiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListFunctionalitiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListFunctionalitiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListFunctionalitiesResponse) GetFunctionalityEntityPaginated() *shared.FunctionalityEntityPaginated {
	if o == nil {
		return nil
	}
	return o.FunctionalityEntityPaginated
}
