// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type ListSignalsEmailTargetsRequest struct {
	// A query string to search the list of targets by.
	Query *string `queryParam:"style=form,explode=true,name=query"`
}

func (o *ListSignalsEmailTargetsRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

type ListSignalsEmailTargetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List all Signals email targets for a team.
	SignalsAPIEmailTargetPaginated *shared.SignalsAPIEmailTargetPaginated
}

func (o *ListSignalsEmailTargetsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListSignalsEmailTargetsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListSignalsEmailTargetsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListSignalsEmailTargetsResponse) GetSignalsAPIEmailTargetPaginated() *shared.SignalsAPIEmailTargetPaginated {
	if o == nil {
		return nil
	}
	return o.SignalsAPIEmailTargetPaginated
}
