// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type PatchV1SignalsEmailTargetsIDRequest struct {
	ID                           string                              `pathParam:"style=simple,explode=false,name=id"`
	PatchV1SignalsEmailTargetsID shared.PatchV1SignalsEmailTargetsID `request:"mediaType=application/json"`
}

func (o *PatchV1SignalsEmailTargetsIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PatchV1SignalsEmailTargetsIDRequest) GetPatchV1SignalsEmailTargetsID() shared.PatchV1SignalsEmailTargetsID {
	if o == nil {
		return shared.PatchV1SignalsEmailTargetsID{}
	}
	return o.PatchV1SignalsEmailTargetsID
}

type PatchV1SignalsEmailTargetsIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchV1SignalsEmailTargetsIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchV1SignalsEmailTargetsIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchV1SignalsEmailTargetsIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
