// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type PatchV1PostMortemsReportsReportIDReasonsReasonIDRequest struct {
	ReportID                                         string                                                  `pathParam:"style=simple,explode=false,name=report_id"`
	ReasonID                                         string                                                  `pathParam:"style=simple,explode=false,name=reason_id"`
	PatchV1PostMortemsReportsReportIDReasonsReasonID shared.PatchV1PostMortemsReportsReportIDReasonsReasonID `request:"mediaType=application/json"`
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDRequest) GetReportID() string {
	if o == nil {
		return ""
	}
	return o.ReportID
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDRequest) GetReasonID() string {
	if o == nil {
		return ""
	}
	return o.ReasonID
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDRequest) GetPatchV1PostMortemsReportsReportIDReasonsReasonID() shared.PatchV1PostMortemsReportsReportIDReasonsReasonID {
	if o == nil {
		return shared.PatchV1PostMortemsReportsReportIDReasonsReasonID{}
	}
	return o.PatchV1PostMortemsReportsReportIDReasonsReasonID
}

type PatchV1PostMortemsReportsReportIDReasonsReasonIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update a contributing factor
	PostMortemsReasonEntity *shared.PostMortemsReasonEntity
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchV1PostMortemsReportsReportIDReasonsReasonIDResponse) GetPostMortemsReasonEntity() *shared.PostMortemsReasonEntity {
	if o == nil {
		return nil
	}
	return o.PostMortemsReasonEntity
}
