// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesRequest struct {
	ExecutionID                                          string                                                      `pathParam:"style=simple,explode=false,name=execution_id"`
	StepID                                               string                                                      `pathParam:"style=simple,explode=false,name=step_id"`
	PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotes shared.PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotes `request:"mediaType=application/json"`
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesRequest) GetExecutionID() string {
	if o == nil {
		return ""
	}
	return o.ExecutionID
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesRequest) GetStepID() string {
	if o == nil {
		return ""
	}
	return o.StepID
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesRequest) GetPatchV1RunbooksExecutionsExecutionIDStepsStepIDVotes() shared.PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotes {
	if o == nil {
		return shared.PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotes{}
	}
	return o.PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotes
}

type PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Allows for upvoting or downvoting an event
	VotesEntity *shared.VotesEntity
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchV1RunbooksExecutionsExecutionIDStepsStepIDVotesResponse) GetVotesEntity() *shared.VotesEntity {
	if o == nil {
		return nil
	}
	return o.VotesEntity
}
