// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type PatchV1AudiencesAudienceIDRequestBody struct {
	// Name of the audience (max 255 characters)
	Name *string `json:"name,omitempty"`
	// Description of the audience (max 4000 characters)
	Description *string `json:"description,omitempty"`
	// Whether this is the default audience
	Default *bool `json:"default,omitempty"`
	// Whether the audience is active or discarded
	Active *bool `json:"active,omitempty"`
}

func (o *PatchV1AudiencesAudienceIDRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PatchV1AudiencesAudienceIDRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PatchV1AudiencesAudienceIDRequestBody) GetDefault() *bool {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *PatchV1AudiencesAudienceIDRequestBody) GetActive() *bool {
	if o == nil {
		return nil
	}
	return o.Active
}

type PatchV1AudiencesAudienceIDRequest struct {
	// Unique identifier of the audience
	AudienceID  string                                 `pathParam:"style=simple,explode=false,name=audience_id"`
	RequestBody *PatchV1AudiencesAudienceIDRequestBody `request:"mediaType=application/json"`
}

func (o *PatchV1AudiencesAudienceIDRequest) GetAudienceID() string {
	if o == nil {
		return ""
	}
	return o.AudienceID
}

func (o *PatchV1AudiencesAudienceIDRequest) GetRequestBody() *PatchV1AudiencesAudienceIDRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PatchV1AudiencesAudienceIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update an existing audience
	AudiencesEntitiesAudienceEntity *shared.AudiencesEntitiesAudienceEntity
}

func (o *PatchV1AudiencesAudienceIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchV1AudiencesAudienceIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchV1AudiencesAudienceIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchV1AudiencesAudienceIDResponse) GetAudiencesEntitiesAudienceEntity() *shared.AudiencesEntitiesAudienceEntity {
	if o == nil {
		return nil
	}
	return o.AudiencesEntitiesAudienceEntity
}
