// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type PostV1IncidentsIncidentIDTasksTaskIDConvertRequest struct {
	TaskID                                      string                                             `pathParam:"style=simple,explode=false,name=task_id"`
	IncidentID                                  string                                             `pathParam:"style=simple,explode=false,name=incident_id"`
	PostV1IncidentsIncidentIDTasksTaskIDConvert shared.PostV1IncidentsIncidentIDTasksTaskIDConvert `request:"mediaType=application/json"`
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertRequest) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertRequest) GetPostV1IncidentsIncidentIDTasksTaskIDConvert() shared.PostV1IncidentsIncidentIDTasksTaskIDConvert {
	if o == nil {
		return shared.PostV1IncidentsIncidentIDTasksTaskIDConvert{}
	}
	return o.PostV1IncidentsIncidentIDTasksTaskIDConvert
}

type PostV1IncidentsIncidentIDTasksTaskIDConvertResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Convert a task to a follow-up
	TaskEntityPaginated *shared.TaskEntityPaginated
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostV1IncidentsIncidentIDTasksTaskIDConvertResponse) GetTaskEntityPaginated() *shared.TaskEntityPaginated {
	if o == nil {
		return nil
	}
	return o.TaskEntityPaginated
}
