// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type UpdateIncidentChatMessageRequest struct {
	MessageID                                              string                                                        `pathParam:"style=simple,explode=false,name=message_id"`
	IncidentID                                             string                                                        `pathParam:"style=simple,explode=false,name=incident_id"`
	PatchV1IncidentsIncidentIDGenericChatMessagesMessageID shared.PatchV1IncidentsIncidentIDGenericChatMessagesMessageID `request:"mediaType=application/json"`
}

func (o *UpdateIncidentChatMessageRequest) GetMessageID() string {
	if o == nil {
		return ""
	}
	return o.MessageID
}

func (o *UpdateIncidentChatMessageRequest) GetIncidentID() string {
	if o == nil {
		return ""
	}
	return o.IncidentID
}

func (o *UpdateIncidentChatMessageRequest) GetPatchV1IncidentsIncidentIDGenericChatMessagesMessageID() shared.PatchV1IncidentsIncidentIDGenericChatMessagesMessageID {
	if o == nil {
		return shared.PatchV1IncidentsIncidentIDGenericChatMessagesMessageID{}
	}
	return o.PatchV1IncidentsIncidentIDGenericChatMessagesMessageID
}

type UpdateIncidentChatMessageResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update an existing generic chat message on an incident.
	EventGenericChatMessageEntity *shared.EventGenericChatMessageEntity
	// A collection of codes that generally means the end user got something wrong in making the request
	BadRequest *shared.BadRequest
	// A collection of codes that generally means the client was not authenticated correctly for the request they want to make
	Unauthorized *shared.Unauthorized
	// Status codes relating to the resource/entity they are requesting not being found or endpoints/routes not existing
	NotFound *shared.NotFound
	// Status codes relating to the client being rate limited by the server
	RateLimited *shared.RateLimited
	// A collection of status codes that generally mean the server failed in an unexpected way
	InternalServerError *shared.InternalServerError
	// Timeouts occurred with the request
	Timeout *shared.Timeout
}

func (o *UpdateIncidentChatMessageResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateIncidentChatMessageResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateIncidentChatMessageResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateIncidentChatMessageResponse) GetEventGenericChatMessageEntity() *shared.EventGenericChatMessageEntity {
	if o == nil {
		return nil
	}
	return o.EventGenericChatMessageEntity
}

func (o *UpdateIncidentChatMessageResponse) GetBadRequest() *shared.BadRequest {
	if o == nil {
		return nil
	}
	return o.BadRequest
}

func (o *UpdateIncidentChatMessageResponse) GetUnauthorized() *shared.Unauthorized {
	if o == nil {
		return nil
	}
	return o.Unauthorized
}

func (o *UpdateIncidentChatMessageResponse) GetNotFound() *shared.NotFound {
	if o == nil {
		return nil
	}
	return o.NotFound
}

func (o *UpdateIncidentChatMessageResponse) GetRateLimited() *shared.RateLimited {
	if o == nil {
		return nil
	}
	return o.RateLimited
}

func (o *UpdateIncidentChatMessageResponse) GetInternalServerError() *shared.InternalServerError {
	if o == nil {
		return nil
	}
	return o.InternalServerError
}

func (o *UpdateIncidentChatMessageResponse) GetTimeout() *shared.Timeout {
	if o == nil {
		return nil
	}
	return o.Timeout
}
