// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-firehydrant-terraform-sdk/internal/sdk/models/shared"
	"net/http"
)

type UpdateConversationCommentRequest struct {
	CommentID                                           string                                                     `pathParam:"style=simple,explode=false,name=comment_id"`
	ConversationID                                      string                                                     `pathParam:"style=simple,explode=false,name=conversation_id"`
	PatchV1ConversationsConversationIDCommentsCommentID shared.PatchV1ConversationsConversationIDCommentsCommentID `request:"mediaType=application/json"`
}

func (o *UpdateConversationCommentRequest) GetCommentID() string {
	if o == nil {
		return ""
	}
	return o.CommentID
}

func (o *UpdateConversationCommentRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

func (o *UpdateConversationCommentRequest) GetPatchV1ConversationsConversationIDCommentsCommentID() shared.PatchV1ConversationsConversationIDCommentsCommentID {
	if o == nil {
		return shared.PatchV1ConversationsConversationIDCommentsCommentID{}
	}
	return o.PatchV1ConversationsConversationIDCommentsCommentID
}

type UpdateConversationCommentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A collection of codes that generally means the end user got something wrong in making the request
	BadRequest *shared.BadRequest
	// A collection of codes that generally means the client was not authenticated correctly for the request they want to make
	Unauthorized *shared.Unauthorized
	// Status codes relating to the resource/entity they are requesting not being found or endpoints/routes not existing
	NotFound *shared.NotFound
	// Status codes relating to the client being rate limited by the server
	RateLimited *shared.RateLimited
	// A collection of status codes that generally mean the server failed in an unexpected way
	InternalServerError *shared.InternalServerError
	// Timeouts occurred with the request
	Timeout *shared.Timeout
}

func (o *UpdateConversationCommentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateConversationCommentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateConversationCommentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateConversationCommentResponse) GetBadRequest() *shared.BadRequest {
	if o == nil {
		return nil
	}
	return o.BadRequest
}

func (o *UpdateConversationCommentResponse) GetUnauthorized() *shared.Unauthorized {
	if o == nil {
		return nil
	}
	return o.Unauthorized
}

func (o *UpdateConversationCommentResponse) GetNotFound() *shared.NotFound {
	if o == nil {
		return nil
	}
	return o.NotFound
}

func (o *UpdateConversationCommentResponse) GetRateLimited() *shared.RateLimited {
	if o == nil {
		return nil
	}
	return o.RateLimited
}

func (o *UpdateConversationCommentResponse) GetInternalServerError() *shared.InternalServerError {
	if o == nil {
		return nil
	}
	return o.InternalServerError
}

func (o *UpdateConversationCommentResponse) GetTimeout() *shared.Timeout {
	if o == nil {
		return nil
	}
	return o.Timeout
}
