// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type UpdateLifecycleMilestoneRequestBody struct {
	// The setting for auto-assigning the milestone's timestamp during incident declaration
	AutoAssignTimestampOnCreate *string `json:"auto_assign_timestamp_on_create,omitempty"`
	// A long-form description of the milestone's purpose
	Description *string `json:"description,omitempty"`
	// The name of the milestone
	Name *string `json:"name,omitempty"`
	// The position of the milestone within the phase. If not provided, the milestone will be added as the last milestone in the phase.
	Position *int `json:"position,omitempty"`
	// The ID of a later milestone that cannot be started until this milestone has a timestamp populated
	RequiredAtMilestoneID *string `json:"required_at_milestone_id,omitempty"`
	// A unique identifier for the milestone. If not provided, one will be generated from the name.
	Slug *string `json:"slug,omitempty"`
}

func (o *UpdateLifecycleMilestoneRequestBody) GetAutoAssignTimestampOnCreate() *string {
	if o == nil {
		return nil
	}
	return o.AutoAssignTimestampOnCreate
}

func (o *UpdateLifecycleMilestoneRequestBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateLifecycleMilestoneRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateLifecycleMilestoneRequestBody) GetPosition() *int {
	if o == nil {
		return nil
	}
	return o.Position
}

func (o *UpdateLifecycleMilestoneRequestBody) GetRequiredAtMilestoneID() *string {
	if o == nil {
		return nil
	}
	return o.RequiredAtMilestoneID
}

func (o *UpdateLifecycleMilestoneRequestBody) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

type UpdateLifecycleMilestoneRequest struct {
	MilestoneID string                               `pathParam:"style=simple,explode=false,name=milestone_id"`
	RequestBody *UpdateLifecycleMilestoneRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateLifecycleMilestoneRequest) GetMilestoneID() string {
	if o == nil {
		return ""
	}
	return o.MilestoneID
}

func (o *UpdateLifecycleMilestoneRequest) GetRequestBody() *UpdateLifecycleMilestoneRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type UpdateLifecycleMilestoneResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update a milestone
	LifecyclesPhaseEntity *shared.LifecyclesPhaseEntity
}

func (o *UpdateLifecycleMilestoneResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateLifecycleMilestoneResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateLifecycleMilestoneResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateLifecycleMilestoneResponse) GetLifecyclesPhaseEntity() *shared.LifecyclesPhaseEntity {
	if o == nil {
		return nil
	}
	return o.LifecyclesPhaseEntity
}
