// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type UpdateRetrospectiveTemplateRequest struct {
	RetrospectiveTemplateID     string                             `pathParam:"style=simple,explode=false,name=retrospective_template_id"`
	UpdateRetrospectiveTemplate shared.UpdateRetrospectiveTemplate `request:"mediaType=application/json"`
}

func (o *UpdateRetrospectiveTemplateRequest) GetRetrospectiveTemplateID() string {
	if o == nil {
		return ""
	}
	return o.RetrospectiveTemplateID
}

func (o *UpdateRetrospectiveTemplateRequest) GetUpdateRetrospectiveTemplate() shared.UpdateRetrospectiveTemplate {
	if o == nil {
		return shared.UpdateRetrospectiveTemplate{}
	}
	return o.UpdateRetrospectiveTemplate
}

type UpdateRetrospectiveTemplateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update a single retrospective template
	RetrospectivesTemplateEntity *shared.RetrospectivesTemplateEntity
}

func (o *UpdateRetrospectiveTemplateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateRetrospectiveTemplateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateRetrospectiveTemplateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateRetrospectiveTemplateResponse) GetRetrospectivesTemplateEntity() *shared.RetrospectivesTemplateEntity {
	if o == nil {
		return nil
	}
	return o.RetrospectivesTemplateEntity
}
