// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type UpdateTeamRequest struct {
	TeamID     string            `pathParam:"style=simple,explode=false,name=team_id"`
	UpdateTeam shared.UpdateTeam `request:"mediaType=application/json"`
}

func (o *UpdateTeamRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *UpdateTeamRequest) GetUpdateTeam() shared.UpdateTeam {
	if o == nil {
		return shared.UpdateTeam{}
	}
	return o.UpdateTeam
}

type UpdateTeamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update a single team from its ID
	Team *shared.Team
}

func (o *UpdateTeamResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateTeamResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateTeamResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateTeamResponse) GetTeam() *shared.Team {
	if o == nil {
		return nil
	}
	return o.Team
}
