// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"net/http"
)

type UpdateNuncConnectionRequest struct {
	NuncConnectionID     string                      `pathParam:"style=simple,explode=false,name=nunc_connection_id"`
	UpdateNuncConnection shared.UpdateNuncConnection `request:"mediaType=application/json"`
}

func (o *UpdateNuncConnectionRequest) GetNuncConnectionID() string {
	if o == nil {
		return ""
	}
	return o.NuncConnectionID
}

func (o *UpdateNuncConnectionRequest) GetUpdateNuncConnection() shared.UpdateNuncConnection {
	if o == nil {
		return shared.UpdateNuncConnection{}
	}
	return o.UpdateNuncConnection
}

type UpdateNuncConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Update your company's information and other components in the specified FireHydrant hosted status page.
	NuncConnection *shared.NuncConnection
}

func (o *UpdateNuncConnectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateNuncConnectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateNuncConnectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateNuncConnectionResponse) GetNuncConnection() *shared.NuncConnection {
	if o == nil {
		return nil
	}
	return o.NuncConnection
}
