// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ChangeTypePaginated model
type ChangeTypePaginated struct {
	Data       []ChangeType        `json:"data,omitempty"`
	Pagination *NullablePagination `json:"pagination,omitempty"`
}

func (o *ChangeTypePaginated) GetData() []ChangeType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ChangeTypePaginated) GetPagination() *NullablePagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
