// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ChangeIdentityPaginated model
type ChangeIdentityPaginated struct {
	Data       []ChangeIdentity    `json:"data,omitempty"`
	Pagination *NullablePagination `json:"pagination,omitempty"`
}

func (o *ChangeIdentityPaginated) GetData() []ChangeIdentity {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ChangeIdentityPaginated) GetPagination() *NullablePagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
