// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateSavedSearch - Create a new saved search for a particular resource type
type CreateSavedSearch struct {
	Name         string         `json:"name"`
	IsPrivate    *bool          `json:"is_private,omitempty"`
	FilterValues map[string]any `json:"filter_values"`
}

func (o *CreateSavedSearch) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateSavedSearch) GetIsPrivate() *bool {
	if o == nil {
		return nil
	}
	return o.IsPrivate
}

func (o *CreateSavedSearch) GetFilterValues() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.FilterValues
}
