// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateNuncConnection struct {
	CompanyName                  *string  `json:"company_name,omitempty"`
	CompanyTosURL                *string  `json:"company_tos_url,omitempty"`
	CompanyWebsite               *string  `json:"company_website,omitempty"`
	ComponentsInfrastructureID   []string `json:"components[infrastructure_id]"`
	ComponentsInfrastructureType []string `json:"components[infrastructure_type]"`
	// Severity matrix condition id
	ConditionsConditionID []string `json:"conditions[condition_id]"`
	// Status page condition to map your severity matrix condition to
	ConditionsNuncCondition []string `json:"conditions[nunc_condition]"`
	Domain                  string   `json:"domain"`
	EnableHistogram         *bool    `json:"enable_histogram,omitempty"`
	ExposedFields           []string `json:"exposed_fields,omitempty"`
	GreetingBody            *string  `json:"greeting_body,omitempty"`
	GreetingTitle           *string  `json:"greeting_title,omitempty"`
	OperationalMessage      *string  `json:"operational_message,omitempty"`
	PrimaryColor            *string  `json:"primary_color,omitempty"`
	SecondaryColor          *string  `json:"secondary_color,omitempty"`
	Title                   *string  `json:"title,omitempty"`
	UIVersion               *int     `json:"ui_version,omitempty"`
}

func (o *CreateNuncConnection) GetCompanyName() *string {
	if o == nil {
		return nil
	}
	return o.CompanyName
}

func (o *CreateNuncConnection) GetCompanyTosURL() *string {
	if o == nil {
		return nil
	}
	return o.CompanyTosURL
}

func (o *CreateNuncConnection) GetCompanyWebsite() *string {
	if o == nil {
		return nil
	}
	return o.CompanyWebsite
}

func (o *CreateNuncConnection) GetComponentsInfrastructureID() []string {
	if o == nil {
		return []string{}
	}
	return o.ComponentsInfrastructureID
}

func (o *CreateNuncConnection) GetComponentsInfrastructureType() []string {
	if o == nil {
		return []string{}
	}
	return o.ComponentsInfrastructureType
}

func (o *CreateNuncConnection) GetConditionsConditionID() []string {
	if o == nil {
		return []string{}
	}
	return o.ConditionsConditionID
}

func (o *CreateNuncConnection) GetConditionsNuncCondition() []string {
	if o == nil {
		return []string{}
	}
	return o.ConditionsNuncCondition
}

func (o *CreateNuncConnection) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *CreateNuncConnection) GetEnableHistogram() *bool {
	if o == nil {
		return nil
	}
	return o.EnableHistogram
}

func (o *CreateNuncConnection) GetExposedFields() []string {
	if o == nil {
		return nil
	}
	return o.ExposedFields
}

func (o *CreateNuncConnection) GetGreetingBody() *string {
	if o == nil {
		return nil
	}
	return o.GreetingBody
}

func (o *CreateNuncConnection) GetGreetingTitle() *string {
	if o == nil {
		return nil
	}
	return o.GreetingTitle
}

func (o *CreateNuncConnection) GetOperationalMessage() *string {
	if o == nil {
		return nil
	}
	return o.OperationalMessage
}

func (o *CreateNuncConnection) GetPrimaryColor() *string {
	if o == nil {
		return nil
	}
	return o.PrimaryColor
}

func (o *CreateNuncConnection) GetSecondaryColor() *string {
	if o == nil {
		return nil
	}
	return o.SecondaryColor
}

func (o *CreateNuncConnection) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *CreateNuncConnection) GetUIVersion() *int {
	if o == nil {
		return nil
	}
	return o.UIVersion
}
