// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateTeamMembershipsInput struct {
	// An incident role ID that this user will automatically assigned if this team is assigned to an incident
	IncidentRoleID *string `json:"incident_role_id,omitempty"`
	ScheduleID     *string `json:"schedule_id,omitempty"`
	UserID         *string `json:"user_id,omitempty"`
}

func (o *CreateTeamMembershipsInput) GetIncidentRoleID() *string {
	if o == nil {
		return nil
	}
	return o.IncidentRoleID
}

func (o *CreateTeamMembershipsInput) GetScheduleID() *string {
	if o == nil {
		return nil
	}
	return o.ScheduleID
}

func (o *CreateTeamMembershipsInput) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

// CreateTeamMsTeamsChannelInput - MS Teams channel identity for channel associated with this team
type CreateTeamMsTeamsChannelInput struct {
	ChannelID string `json:"channel_id"`
	MsTeamID  string `json:"ms_team_id"`
}

func (o *CreateTeamMsTeamsChannelInput) GetChannelID() string {
	if o == nil {
		return ""
	}
	return o.ChannelID
}

func (o *CreateTeamMsTeamsChannelInput) GetMsTeamID() string {
	if o == nil {
		return ""
	}
	return o.MsTeamID
}

// CreateTeam - Create a new team
type CreateTeam struct {
	Description *string `json:"description,omitempty"`
	// A list of email addresses to invite to join the organization and automatically add to this team. If an email already has a pending invitation, the team will be added to their existing invitation.
	InviteEmails     []string                     `json:"invite_emails,omitempty"`
	MembershipsInput []CreateTeamMembershipsInput `json:"memberships,omitempty"`
	// MS Teams channel identity for channel associated with this team
	MsTeamsChannelInput *CreateTeamMsTeamsChannelInput `json:"ms_teams_channel,omitempty"`
	Name                string                         `json:"name"`
	// The Slack channel ID associated with this team. This may be the reference in FireHydrant's system (i.e. UUID) or the ID value from Slack (e.g. C1234567890).
	//
	SlackChannelID *string `json:"slack_channel_id,omitempty"`
	Slug           *string `json:"slug,omitempty"`
}

func (o *CreateTeam) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTeam) GetInviteEmails() []string {
	if o == nil {
		return nil
	}
	return o.InviteEmails
}

func (o *CreateTeam) GetMembershipsInput() []CreateTeamMembershipsInput {
	if o == nil {
		return nil
	}
	return o.MembershipsInput
}

func (o *CreateTeam) GetMsTeamsChannelInput() *CreateTeamMsTeamsChannelInput {
	if o == nil {
		return nil
	}
	return o.MsTeamsChannelInput
}

func (o *CreateTeam) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateTeam) GetSlackChannelID() *string {
	if o == nil {
		return nil
	}
	return o.SlackChannelID
}

func (o *CreateTeam) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}
