// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CreateIncidentChangeEvent - Add a related change to an incident. Changes added to an incident can be causes, fixes, or suspects. To remove a change from an incident, the type field should be set to dismissed.
type CreateIncidentChangeEvent struct {
	// The ID of the change event to associate
	ChangeEventID string `json:"change_event_id"`
	Type          string `json:"type"`
	// A short description about why this change event is related
	Why *string `json:"why,omitempty"`
}

func (o *CreateIncidentChangeEvent) GetChangeEventID() string {
	if o == nil {
		return ""
	}
	return o.ChangeEventID
}

func (o *CreateIncidentChangeEvent) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *CreateIncidentChangeEvent) GetWhy() *string {
	if o == nil {
		return nil
	}
	return o.Why
}
