// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EntitlementEntityPaginated model
type EntitlementEntityPaginated struct {
	Data       []EntitlementEntity       `json:"data,omitempty"`
	Pagination *NullablePaginationEntity `json:"pagination,omitempty"`
}

func (o *EntitlementEntityPaginated) GetData() []EntitlementEntity {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *EntitlementEntityPaginated) GetPagination() *NullablePaginationEntity {
	if o == nil {
		return nil
	}
	return o.Pagination
}
