// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Error model
type Error struct {
	// A stable code on which to match errors
	Code     *string  `json:"code,omitempty"`
	Detail   *string  `json:"detail,omitempty"`
	Messages []string `json:"messages,omitempty"`
	// An object with additional error metadata
	Meta map[string]any `json:"meta,omitempty"`
}

func (o *Error) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Error) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *Error) GetMessages() []string {
	if o == nil {
		return nil
	}
	return o.Messages
}

func (o *Error) GetMeta() map[string]any {
	if o == nil {
		return nil
	}
	return o.Meta
}
