// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// IncidentsRoleAssignmentPaginated - Incidents_RoleAssignmentPaginated model
type IncidentsRoleAssignmentPaginated struct {
	Data       []IncidentsRoleAssignment `json:"data,omitempty"`
	Pagination *NullablePagination       `json:"pagination,omitempty"`
}

func (o *IncidentsRoleAssignmentPaginated) GetData() []IncidentsRoleAssignment {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *IncidentsRoleAssignmentPaginated) GetPagination() *NullablePagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
