// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// IncidentsMilestonePaginated - Incidents_MilestonePaginated model
type IncidentsMilestonePaginated struct {
	Data       []IncidentsMilestone `json:"data,omitempty"`
	Pagination *NullablePagination  `json:"pagination,omitempty"`
}

func (o *IncidentsMilestonePaginated) GetData() []IncidentsMilestone {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *IncidentsMilestonePaginated) GetPagination() *NullablePagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
