// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// IncidentRolePaginated model
type IncidentRolePaginated struct {
	Data       []IncidentRole      `json:"data,omitempty"`
	Pagination *NullablePagination `json:"pagination,omitempty"`
}

func (o *IncidentRolePaginated) GetData() []IncidentRole {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *IncidentRolePaginated) GetPagination() *NullablePagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}
