// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/internal/utils"
	"time"
)

// IntegrationsConnectionStatusEntityData - Additional unstructured data about the status check.
type IntegrationsConnectionStatusEntityData struct {
}

// IntegrationsConnectionStatusEntity - Integrations_ConnectionStatusEntity model
type IntegrationsConnectionStatusEntity struct {
	CheckType    *string    `json:"check_type,omitempty"`
	CheckedAt    *time.Time `json:"checked_at,omitempty"`
	ConnectionID *string    `json:"connection_id,omitempty"`
	// Additional unstructured data about the status check.
	Data            *IntegrationsConnectionStatusEntityData `json:"data,omitempty"`
	ErrorType       *string                                 `json:"error_type,omitempty"`
	IntegrationSlug *string                                 `json:"integration_slug,omitempty"`
	Message         *string                                 `json:"message,omitempty"`
	PerformedBy     *NullableAuthorEntity                   `json:"performed_by,omitempty"`
	Status          *string                                 `json:"status,omitempty"`
}

func (i IntegrationsConnectionStatusEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IntegrationsConnectionStatusEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *IntegrationsConnectionStatusEntity) GetCheckType() *string {
	if o == nil {
		return nil
	}
	return o.CheckType
}

func (o *IntegrationsConnectionStatusEntity) GetCheckedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CheckedAt
}

func (o *IntegrationsConnectionStatusEntity) GetConnectionID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionID
}

func (o *IntegrationsConnectionStatusEntity) GetData() *IntegrationsConnectionStatusEntityData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *IntegrationsConnectionStatusEntity) GetErrorType() *string {
	if o == nil {
		return nil
	}
	return o.ErrorType
}

func (o *IntegrationsConnectionStatusEntity) GetIntegrationSlug() *string {
	if o == nil {
		return nil
	}
	return o.IntegrationSlug
}

func (o *IntegrationsConnectionStatusEntity) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *IntegrationsConnectionStatusEntity) GetPerformedBy() *NullableAuthorEntity {
	if o == nil {
		return nil
	}
	return o.PerformedBy
}

func (o *IntegrationsConnectionStatusEntity) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
