// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// IntegrationsAwsCloudtrailBatchEntityPaginated - Integrations_Aws_CloudtrailBatchEntityPaginated model
type IntegrationsAwsCloudtrailBatchEntityPaginated struct {
	Data       []IntegrationsAwsCloudtrailBatchEntity `json:"data,omitempty"`
	Pagination *NullablePaginationEntity              `json:"pagination,omitempty"`
}

func (o *IntegrationsAwsCloudtrailBatchEntityPaginated) GetData() []IntegrationsAwsCloudtrailBatchEntity {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *IntegrationsAwsCloudtrailBatchEntityPaginated) GetPagination() *NullablePaginationEntity {
	if o == nil {
		return nil
	}
	return o.Pagination
}
