// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type MetricsMilestonesFunnelColumn struct {
	// The UUID of the milestone
	ID *string `json:"id,omitempty"`
	// The name of the milestone
	Label *string `json:"label,omitempty"`
	// The slug of the milestone
	Name *string `json:"name,omitempty"`
	// The description of the milestone
	Tooltip *string `json:"tooltip,omitempty"`
}

func (o *MetricsMilestonesFunnelColumn) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *MetricsMilestonesFunnelColumn) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *MetricsMilestonesFunnelColumn) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *MetricsMilestonesFunnelColumn) GetTooltip() *string {
	if o == nil {
		return nil
	}
	return o.Tooltip
}
