// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableSignalsAPIGroupingEntityActionEntityFyiEntity struct {
	SlackChannels []IntegrationsSlackSlackChannelEntity `json:"slack_channels,omitempty"`
}

func (o *NullableSignalsAPIGroupingEntityActionEntityFyiEntity) GetSlackChannels() []IntegrationsSlackSlackChannelEntity {
	if o == nil {
		return nil
	}
	return o.SlackChannels
}
