// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableNuncComponentGroupEntity struct {
	ComponentGroupID *string `json:"component_group_id,omitempty"`
	ID               *string `json:"id,omitempty"`
	Name             *string `json:"name,omitempty"`
	Position         *int    `json:"position,omitempty"`
}

func (o *NullableNuncComponentGroupEntity) GetComponentGroupID() *string {
	if o == nil {
		return nil
	}
	return o.ComponentGroupID
}

func (o *NullableNuncComponentGroupEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NullableNuncComponentGroupEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *NullableNuncComponentGroupEntity) GetPosition() *int {
	if o == nil {
		return nil
	}
	return o.Position
}
