// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableRulesRuleEntity struct {
	// An unstructured object of key/value pairs describing the logic for applying the rule.
	Logic    map[string]any                `json:"logic,omitempty"`
	UserData *NullableFHTypesGenericEntity `json:"user_data,omitempty"`
}

func (o *NullableRulesRuleEntity) GetLogic() map[string]any {
	if o == nil {
		return nil
	}
	return o.Logic
}

func (o *NullableRulesRuleEntity) GetUserData() *NullableFHTypesGenericEntity {
	if o == nil {
		return nil
	}
	return o.UserData
}
