// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/internal/utils"
	"time"
)

type NullableExternalResourceEntity struct {
	ConnectionType           *string    `json:"connection_type,omitempty"`
	ConnectionName           *string    `json:"connection_name,omitempty"`
	ConnectionFullFaviconURL *string    `json:"connection_full_favicon_url,omitempty"`
	ConnectionID             *string    `json:"connection_id,omitempty"`
	RemoteID                 *string    `json:"remote_id,omitempty"`
	RemoteURL                *string    `json:"remote_url,omitempty"`
	CreatedAt                *time.Time `json:"created_at,omitempty"`
	UpdatedAt                *time.Time `json:"updated_at,omitempty"`
	Name                     *string    `json:"name,omitempty"`
}

func (n NullableExternalResourceEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NullableExternalResourceEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *NullableExternalResourceEntity) GetConnectionType() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionType
}

func (o *NullableExternalResourceEntity) GetConnectionName() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionName
}

func (o *NullableExternalResourceEntity) GetConnectionFullFaviconURL() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionFullFaviconURL
}

func (o *NullableExternalResourceEntity) GetConnectionID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionID
}

func (o *NullableExternalResourceEntity) GetRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.RemoteID
}

func (o *NullableExternalResourceEntity) GetRemoteURL() *string {
	if o == nil {
		return nil
	}
	return o.RemoteURL
}

func (o *NullableExternalResourceEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *NullableExternalResourceEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *NullableExternalResourceEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
