// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableSignalsAPIEscalationPolicyHandoffStepEntity struct {
	ID     *string                         `json:"id,omitempty"`
	Target *NullableSignalsAPITargetEntity `json:"target,omitempty"`
}

func (o *NullableSignalsAPIEscalationPolicyHandoffStepEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NullableSignalsAPIEscalationPolicyHandoffStepEntity) GetTarget() *NullableSignalsAPITargetEntity {
	if o == nil {
		return nil
	}
	return o.Target
}
