// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableIntegrationsSlackSlackChannel struct {
	ID             *string `json:"id,omitempty"`
	Name           *string `json:"name,omitempty"`
	SlackChannelID *string `json:"slack_channel_id,omitempty"`
}

func (o *NullableIntegrationsSlackSlackChannel) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NullableIntegrationsSlackSlackChannel) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *NullableIntegrationsSlackSlackChannel) GetSlackChannelID() *string {
	if o == nil {
		return nil
	}
	return o.SlackChannelID
}
