// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableOrganization struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (o *NullableOrganization) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NullableOrganization) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
