// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NullableIntegrationsZendeskSupportIssueCustomer struct {
	// UUID of the Customer
	ID *string `json:"id,omitempty"`
	// Name of the Customer
	Name *string `json:"name,omitempty"`
}

func (o *NullableIntegrationsZendeskSupportIssueCustomer) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NullableIntegrationsZendeskSupportIssueCustomer) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
