// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PostMortemsQuestionType - PostMortems_QuestionType model
type PostMortemsQuestionType struct {
	AvailableOptions []string `json:"available_options,omitempty"`
	ID               *string  `json:"id,omitempty"`
	IsRequired       *bool    `json:"is_required,omitempty"`
	Kind             *string  `json:"kind,omitempty"`
	Title            *string  `json:"title,omitempty"`
	Tooltip          *string  `json:"tooltip,omitempty"`
}

func (o *PostMortemsQuestionType) GetAvailableOptions() []string {
	if o == nil {
		return nil
	}
	return o.AvailableOptions
}

func (o *PostMortemsQuestionType) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PostMortemsQuestionType) GetIsRequired() *bool {
	if o == nil {
		return nil
	}
	return o.IsRequired
}

func (o *PostMortemsQuestionType) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

func (o *PostMortemsQuestionType) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *PostMortemsQuestionType) GetTooltip() *string {
	if o == nil {
		return nil
	}
	return o.Tooltip
}
