// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResolveIncident struct {
	// The slug of any milestone in the post-incident or closed phase to set on the incident (and its children, if `resolve_children` os set). Must be one of the configured milestones available on this incident.
	Milestone *string `json:"milestone,omitempty"`
}

func (o *ResolveIncident) GetMilestone() *string {
	if o == nil {
		return nil
	}
	return o.Milestone
}
