// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ShareIncidentRetrospectives struct {
	// An array of retrospective IDs to share
	RetrospectiveIds []string `json:"retrospective_ids"`
	// An array of team IDs with whom to share the report
	TeamIds []string `json:"team_ids,omitempty"`
	// An array of user IDs with whom to share the report
	UserIds []string `json:"user_ids,omitempty"`
}

func (o *ShareIncidentRetrospectives) GetRetrospectiveIds() []string {
	if o == nil {
		return []string{}
	}
	return o.RetrospectiveIds
}

func (o *ShareIncidentRetrospectives) GetTeamIds() []string {
	if o == nil {
		return nil
	}
	return o.TeamIds
}

func (o *ShareIncidentRetrospectives) GetUserIds() []string {
	if o == nil {
		return nil
	}
	return o.UserIds
}
