// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/internal/utils"
	"time"
)

type SignalsAPIOrganizationOnCallRotationEntity struct {
	CreatedAt    *time.Time                           `json:"created_at,omitempty"`
	CreatedBy    *NullableAuthorEntity                `json:"created_by,omitempty"`
	CurrentShift *NullableSignalsAPIOnCallShiftEntity `json:"current_shift,omitempty"`
	Description  *string                              `json:"description,omitempty"`
	ID           *string                              `json:"id,omitempty"`
	Name         *string                              `json:"name,omitempty"`
	NextShift    *NullableSignalsAPIOnCallShiftEntity `json:"next_shift,omitempty"`
	TimeZone     *string                              `json:"time_zone,omitempty"`
	UpdatedAt    *time.Time                           `json:"updated_at,omitempty"`
}

func (s SignalsAPIOrganizationOnCallRotationEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SignalsAPIOrganizationOnCallRotationEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetCreatedBy() *NullableAuthorEntity {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetCurrentShift() *NullableSignalsAPIOnCallShiftEntity {
	if o == nil {
		return nil
	}
	return o.CurrentShift
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetNextShift() *NullableSignalsAPIOnCallShiftEntity {
	if o == nil {
		return nil
	}
	return o.NextShift
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetTimeZone() *string {
	if o == nil {
		return nil
	}
	return o.TimeZone
}

func (o *SignalsAPIOrganizationOnCallRotationEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
