// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/internal/utils"
	"time"
)

type SlimRunbookEntity struct {
	AttachmentRule *NullableRulesRuleEntity `json:"attachment_rule,omitempty"`
	// categories the runbook applies to
	Categories  []string                `json:"categories,omitempty"`
	CreatedAt   *time.Time              `json:"created_at,omitempty"`
	Description *string                 `json:"description,omitempty"`
	ID          *string                 `json:"id,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Owner       *NullableTeamEntityLite `json:"owner,omitempty"`
	Summary     *string                 `json:"summary,omitempty"`
	Type        *string                 `json:"type,omitempty"`
	UpdatedAt   *time.Time              `json:"updated_at,omitempty"`
}

func (s SlimRunbookEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SlimRunbookEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SlimRunbookEntity) GetAttachmentRule() *NullableRulesRuleEntity {
	if o == nil {
		return nil
	}
	return o.AttachmentRule
}

func (o *SlimRunbookEntity) GetCategories() []string {
	if o == nil {
		return nil
	}
	return o.Categories
}

func (o *SlimRunbookEntity) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *SlimRunbookEntity) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *SlimRunbookEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SlimRunbookEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *SlimRunbookEntity) GetOwner() *NullableTeamEntityLite {
	if o == nil {
		return nil
	}
	return o.Owner
}

func (o *SlimRunbookEntity) GetSummary() *string {
	if o == nil {
		return nil
	}
	return o.Summary
}

func (o *SlimRunbookEntity) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *SlimRunbookEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
