// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/internal/utils"
	"time"
)

// TicketingProjectsProjectListItemEntity - Ticketing_Projects_ProjectListItemEntity model
type TicketingProjectsProjectListItemEntity struct {
	Config         *NullableTicketingProjectConfigEntity   `json:"config,omitempty"`
	ConnectionSlug *string                                 `json:"connection_slug,omitempty"`
	FieldMap       *NullableTicketingProjectFieldMapEntity `json:"field_map,omitempty"`
	ID             *string                                 `json:"id,omitempty"`
	Name           *string                                 `json:"name,omitempty"`
	UpdatedAt      *time.Time                              `json:"updated_at,omitempty"`
}

func (t TicketingProjectsProjectListItemEntity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TicketingProjectsProjectListItemEntity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TicketingProjectsProjectListItemEntity) GetConfig() *NullableTicketingProjectConfigEntity {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *TicketingProjectsProjectListItemEntity) GetConnectionSlug() *string {
	if o == nil {
		return nil
	}
	return o.ConnectionSlug
}

func (o *TicketingProjectsProjectListItemEntity) GetFieldMap() *NullableTicketingProjectFieldMapEntity {
	if o == nil {
		return nil
	}
	return o.FieldMap
}

func (o *TicketingProjectsProjectListItemEntity) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TicketingProjectsProjectListItemEntity) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TicketingProjectsProjectListItemEntity) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
