// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TicketingProjectFieldMapCasesEntity struct {
	ExternalValue *NullableTicketingProjectFieldMapExternalValueEntity `json:"external_value,omitempty"`
	// An unstructured object of key/value pairs describing the logic for applying the rule.
	Logic map[string]any `json:"logic,omitempty"`
}

func (o *TicketingProjectFieldMapCasesEntity) GetExternalValue() *NullableTicketingProjectFieldMapExternalValueEntity {
	if o == nil {
		return nil
	}
	return o.ExternalValue
}

func (o *TicketingProjectFieldMapCasesEntity) GetLogic() map[string]any {
	if o == nil {
		return nil
	}
	return o.Logic
}
