// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpdateVote - Upvote or downvote an object
type UpdateVote struct {
	// The direction you would like to vote, or if you dig it
	Direction string `json:"direction"`
}

func (o *UpdateVote) GetDirection() string {
	if o == nil {
		return ""
	}
	return o.Direction
}
