workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    firehydrant-oas:
        inputs:
            - location: ${GITHUB_WORKSPACE}/openapi.json
        overlays:
            - location: ./.speakeasy/terraform-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/firehydrant/firehydrant/firehydrant-oas
targets:
    firehydrant-terraform-sdk:
        target: terraform
        source: firehydrant-oas
        publish:
            terraform:
                gpgPrivateKey: $terraform_gpg_private_key
                gpgPassPhrase: $terraform_gpg_passphrase
