// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/diag"
)

func (r *AudiencesEntitiesAudiencesEntitiesDataSourceModel) ToOperationsListAudiencesRequest(ctx context.Context) (*operations.ListAudiencesRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	includeArchived := new(bool)
	if !r.IncludeArchived.IsUnknown() && !r.IncludeArchived.IsNull() {
		*includeArchived = r.IncludeArchived.ValueBool()
	} else {
		includeArchived = nil
	}
	out := operations.ListAudiencesRequest{
		IncludeArchived: includeArchived,
	}

	return &out, diags
}
