// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/operations"
	customTypes "github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/types"
	"github.com/hashicorp/terraform-plugin-framework/diag"
)

func (r *MetricsInfrastructureMetricsesEntitiesDataSourceModel) ToOperationsListInfrastructureMetricsRequest(ctx context.Context) (*operations.ListInfrastructureMetricsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var infraType string
	infraType = r.InfraType.ValueString()

	var infraID string
	infraID = r.InfraID.ValueString()

	startDate := new(customTypes.Date)
	if !r.StartDate.IsUnknown() && !r.StartDate.IsNull() {
		startDate = customTypes.MustNewDateFromString(r.StartDate.ValueString())
	} else {
		startDate = nil
	}
	endDate := new(customTypes.Date)
	if !r.EndDate.IsUnknown() && !r.EndDate.IsNull() {
		endDate = customTypes.MustNewDateFromString(r.EndDate.ValueString())
	} else {
		endDate = nil
	}
	out := operations.ListInfrastructureMetricsRequest{
		InfraType: infraType,
		InfraID:   infraID,
		StartDate: startDate,
		EndDate:   endDate,
	}

	return &out, diags
}
