// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	tfTypes "github.com/firehydrant/terraform-provider-firehydrant/internal/provider/types"
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/operations"
	"github.com/firehydrant/terraform-provider-firehydrant/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *RetrospectivesTemplateResourceModel) RefreshFromSharedRetrospectivesTemplate(ctx context.Context, resp *shared.RetrospectivesTemplate) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Description = types.StringPointerValue(resp.Description)
		if resp.Fields != nil {
			r.Fields = []tfTypes.RetrospectivesField{}
			if len(r.Fields) > len(resp.Fields) {
				r.Fields = r.Fields[:len(resp.Fields)]
			}
			for fieldsCount, fieldsItem := range resp.Fields {
				var fields tfTypes.RetrospectivesField
				fields.HelpText = types.StringPointerValue(fieldsItem.HelpText)
				fields.ID = types.StringPointerValue(fieldsItem.ID)
				fields.IsRequired = types.BoolPointerValue(fieldsItem.IsRequired)
				fields.Label = types.StringPointerValue(fieldsItem.Label)
				if fieldsItem.PermissibleValues != nil {
					fields.PermissibleValues = make([]types.String, 0, len(fieldsItem.PermissibleValues))
					for _, v := range fieldsItem.PermissibleValues {
						fields.PermissibleValues = append(fields.PermissibleValues, types.StringValue(v))
					}
				}
				if fieldsItem.Schema != nil {
					fields.Schema = make([]types.String, 0, len(fieldsItem.Schema))
					for _, v := range fieldsItem.Schema {
						fields.Schema = append(fields.Schema, types.StringValue(v))
					}
				}
				fields.Type = types.StringPointerValue(fieldsItem.Type)
				if fieldsCount+1 > len(r.Fields) {
					r.Fields = append(r.Fields, fields)
				} else {
					r.Fields[fieldsCount].HelpText = fields.HelpText
					r.Fields[fieldsCount].ID = fields.ID
					r.Fields[fieldsCount].IsRequired = fields.IsRequired
					r.Fields[fieldsCount].Label = fields.Label
					r.Fields[fieldsCount].PermissibleValues = fields.PermissibleValues
					r.Fields[fieldsCount].Schema = fields.Schema
					r.Fields[fieldsCount].Type = fields.Type
				}
			}
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.IsDefault = types.BoolPointerValue(resp.IsDefault)
		r.Name = types.StringPointerValue(resp.Name)
		if resp.Sections != nil {
			r.Sections = []tfTypes.RetrospectivesTemplateIncidentSection{}
			if len(r.Sections) > len(resp.Sections) {
				r.Sections = r.Sections[:len(resp.Sections)]
			}
			for sectionsCount, sectionsItem := range resp.Sections {
				var sections tfTypes.RetrospectivesTemplateIncidentSection
				if sectionsItem.Elements != nil {
					sections.Elements = make([]types.String, 0, len(sectionsItem.Elements))
					for _, v := range sectionsItem.Elements {
						sections.Elements = append(sections.Elements, types.StringValue(v))
					}
				}
				sections.Slug = types.StringPointerValue(sectionsItem.Slug)
				if sectionsCount+1 > len(r.Sections) {
					r.Sections = append(r.Sections, sections)
				} else {
					r.Sections[sectionsCount].Elements = sections.Elements
					r.Sections[sectionsCount].Slug = sections.Slug
				}
			}
		}
	}

	return diags
}

func (r *RetrospectivesTemplateResourceModel) ToOperationsDeleteRetrospectiveTemplateRequest(ctx context.Context) (*operations.DeleteRetrospectiveTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var retrospectiveTemplateID string
	retrospectiveTemplateID = r.ID.ValueString()

	out := operations.DeleteRetrospectiveTemplateRequest{
		RetrospectiveTemplateID: retrospectiveTemplateID,
	}

	return &out, diags
}

func (r *RetrospectivesTemplateResourceModel) ToOperationsGetRetrospectiveTemplateRequest(ctx context.Context) (*operations.GetRetrospectiveTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var retrospectiveTemplateID string
	retrospectiveTemplateID = r.ID.ValueString()

	out := operations.GetRetrospectiveTemplateRequest{
		RetrospectiveTemplateID: retrospectiveTemplateID,
	}

	return &out, diags
}

func (r *RetrospectivesTemplateResourceModel) ToOperationsUpdateRetrospectiveTemplateRequest(ctx context.Context) (*operations.UpdateRetrospectiveTemplateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var retrospectiveTemplateID string
	retrospectiveTemplateID = r.ID.ValueString()

	updateRetrospectiveTemplate, updateRetrospectiveTemplateDiags := r.ToSharedUpdateRetrospectiveTemplate(ctx)
	diags.Append(updateRetrospectiveTemplateDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateRetrospectiveTemplateRequest{
		RetrospectiveTemplateID:     retrospectiveTemplateID,
		UpdateRetrospectiveTemplate: *updateRetrospectiveTemplate,
	}

	return &out, diags
}

func (r *RetrospectivesTemplateResourceModel) ToSharedCreateRetrospectiveTemplate(ctx context.Context) (*shared.CreateRetrospectiveTemplate, diag.Diagnostics) {
	var diags diag.Diagnostics

	var description string
	description = r.Description.ValueString()

	var fieldsHelpText []string
	if r.FieldsHelpText != nil {
		fieldsHelpText = make([]string, 0, len(r.FieldsHelpText))
		for _, fieldsHelpTextItem := range r.FieldsHelpText {
			fieldsHelpText = append(fieldsHelpText, fieldsHelpTextItem.ValueString())
		}
	}
	var fieldsIsRequired []bool
	if r.FieldsIsRequired != nil {
		fieldsIsRequired = make([]bool, 0, len(r.FieldsIsRequired))
		for _, fieldsIsRequiredItem := range r.FieldsIsRequired {
			fieldsIsRequired = append(fieldsIsRequired, fieldsIsRequiredItem.ValueBool())
		}
	}
	fieldsLabel := make([]string, 0, len(r.FieldsLabel))
	for _, fieldsLabelItem := range r.FieldsLabel {
		fieldsLabel = append(fieldsLabel, fieldsLabelItem.ValueString())
	}
	var fieldsPermissibleValues []string
	if r.FieldsPermissibleValues != nil {
		fieldsPermissibleValues = make([]string, 0, len(r.FieldsPermissibleValues))
		for _, fieldsPermissibleValuesItem := range r.FieldsPermissibleValues {
			fieldsPermissibleValues = append(fieldsPermissibleValues, fieldsPermissibleValuesItem.ValueString())
		}
	}
	var fieldsSchema []string
	if r.FieldsSchema != nil {
		fieldsSchema = make([]string, 0, len(r.FieldsSchema))
		for _, fieldsSchemaItem := range r.FieldsSchema {
			fieldsSchema = append(fieldsSchema, fieldsSchemaItem.ValueString())
		}
	}
	fieldsType := make([]string, 0, len(r.FieldsType))
	for _, fieldsTypeItem := range r.FieldsType {
		fieldsType = append(fieldsType, fieldsTypeItem.ValueString())
	}
	isDefault := new(bool)
	if !r.IsDefault.IsUnknown() && !r.IsDefault.IsNull() {
		*isDefault = r.IsDefault.ValueBool()
	} else {
		isDefault = nil
	}
	var name string
	name = r.Name.ValueString()

	sectionsElements := make([]string, 0, len(r.SectionsElements))
	for _, sectionsElementsItem := range r.SectionsElements {
		sectionsElements = append(sectionsElements, sectionsElementsItem.ValueString())
	}
	sectionsSlug := make([]string, 0, len(r.SectionsSlug))
	for _, sectionsSlugItem := range r.SectionsSlug {
		sectionsSlug = append(sectionsSlug, sectionsSlugItem.ValueString())
	}
	out := shared.CreateRetrospectiveTemplate{
		Description:             description,
		FieldsHelpText:          fieldsHelpText,
		FieldsIsRequired:        fieldsIsRequired,
		FieldsLabel:             fieldsLabel,
		FieldsPermissibleValues: fieldsPermissibleValues,
		FieldsSchema:            fieldsSchema,
		FieldsType:              fieldsType,
		IsDefault:               isDefault,
		Name:                    name,
		SectionsElements:        sectionsElements,
		SectionsSlug:            sectionsSlug,
	}

	return &out, diags
}

func (r *RetrospectivesTemplateResourceModel) ToSharedUpdateRetrospectiveTemplate(ctx context.Context) (*shared.UpdateRetrospectiveTemplate, diag.Diagnostics) {
	var diags diag.Diagnostics

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	var fieldsHelpText []string
	if r.FieldsHelpText != nil {
		fieldsHelpText = make([]string, 0, len(r.FieldsHelpText))
		for _, fieldsHelpTextItem := range r.FieldsHelpText {
			fieldsHelpText = append(fieldsHelpText, fieldsHelpTextItem.ValueString())
		}
	}
	var fieldsIsRequired []bool
	if r.FieldsIsRequired != nil {
		fieldsIsRequired = make([]bool, 0, len(r.FieldsIsRequired))
		for _, fieldsIsRequiredItem := range r.FieldsIsRequired {
			fieldsIsRequired = append(fieldsIsRequired, fieldsIsRequiredItem.ValueBool())
		}
	}
	fieldsLabel := make([]string, 0, len(r.FieldsLabel))
	for _, fieldsLabelItem := range r.FieldsLabel {
		fieldsLabel = append(fieldsLabel, fieldsLabelItem.ValueString())
	}
	var fieldsPermissibleValues []string
	if r.FieldsPermissibleValues != nil {
		fieldsPermissibleValues = make([]string, 0, len(r.FieldsPermissibleValues))
		for _, fieldsPermissibleValuesItem := range r.FieldsPermissibleValues {
			fieldsPermissibleValues = append(fieldsPermissibleValues, fieldsPermissibleValuesItem.ValueString())
		}
	}
	var fieldsSchema []string
	if r.FieldsSchema != nil {
		fieldsSchema = make([]string, 0, len(r.FieldsSchema))
		for _, fieldsSchemaItem := range r.FieldsSchema {
			fieldsSchema = append(fieldsSchema, fieldsSchemaItem.ValueString())
		}
	}
	fieldsType := make([]string, 0, len(r.FieldsType))
	for _, fieldsTypeItem := range r.FieldsType {
		fieldsType = append(fieldsType, fieldsTypeItem.ValueString())
	}
	isDefault := new(bool)
	if !r.IsDefault.IsUnknown() && !r.IsDefault.IsNull() {
		*isDefault = r.IsDefault.ValueBool()
	} else {
		isDefault = nil
	}
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	sectionsElements := make([]string, 0, len(r.SectionsElements))
	for _, sectionsElementsItem := range r.SectionsElements {
		sectionsElements = append(sectionsElements, sectionsElementsItem.ValueString())
	}
	sectionsSlug := make([]string, 0, len(r.SectionsSlug))
	for _, sectionsSlugItem := range r.SectionsSlug {
		sectionsSlug = append(sectionsSlug, sectionsSlugItem.ValueString())
	}
	out := shared.UpdateRetrospectiveTemplate{
		Description:             description,
		FieldsHelpText:          fieldsHelpText,
		FieldsIsRequired:        fieldsIsRequired,
		FieldsLabel:             fieldsLabel,
		FieldsPermissibleValues: fieldsPermissibleValues,
		FieldsSchema:            fieldsSchema,
		FieldsType:              fieldsType,
		IsDefault:               isDefault,
		Name:                    name,
		SectionsElements:        sectionsElements,
		SectionsSlug:            sectionsSlug,
	}

	return &out, diags
}
