// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CreateTeamMsTeamsChannelInput struct {
	ChannelID types.String `tfsdk:"channel_id"`
	MsTeamID  types.String `tfsdk:"ms_team_id"`
}
