// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CreateTeamEscalationPolicyHigh struct {
	HandoffStep *CreateTeamEscalationPolicyHighHandoffStep `tfsdk:"handoff_step"`
	Repetitions types.Int32                                `tfsdk:"repetitions"`
}
