// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ExternalResourceEntity struct {
	ConnectionFullFaviconURL types.String `tfsdk:"connection_full_favicon_url"`
	ConnectionID             types.String `tfsdk:"connection_id"`
	ConnectionName           types.String `tfsdk:"connection_name"`
	ConnectionType           types.String `tfsdk:"connection_type"`
	CreatedAt                types.String `tfsdk:"created_at"`
	Name                     types.String `tfsdk:"name"`
	RemoteID                 types.String `tfsdk:"remote_id"`
	RemoteURL                types.String `tfsdk:"remote_url"`
	UpdatedAt                types.String `tfsdk:"updated_at"`
}
