// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NullableCalendarsEvent struct {
	CreatedAt       types.String `tfsdk:"created_at"`
	Description     types.String `tfsdk:"description"`
	EndsAt          types.String `tfsdk:"ends_at"`
	ID              types.String `tfsdk:"id"`
	ProviderIconURL types.String `tfsdk:"provider_icon_url"`
	ProviderURL     types.String `tfsdk:"provider_url"`
	StartsAt        types.String `tfsdk:"starts_at"`
	Summary         types.String `tfsdk:"summary"`
	UpdatedAt       types.String `tfsdk:"updated_at"`
}
