// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NullableIncidentEntity struct {
	Active                  types.Bool                             `tfsdk:"active"`
	AiIncidentSummary       types.String                           `tfsdk:"ai_incident_summary"`
	ChannelID               types.String                           `tfsdk:"channel_id"`
	ChannelName             types.String                           `tfsdk:"channel_name"`
	ChannelReference        types.String                           `tfsdk:"channel_reference"`
	ChannelStatus           types.String                           `tfsdk:"channel_status"`
	ConferenceBridges       []IncidentsConferenceBridgeEntity      `tfsdk:"conference_bridges"`
	ContextObject           *NullableIncidentsContextObjectEntity  `tfsdk:"context_object"`
	Conversations           []ConversationsAPIEntitiesReference    `tfsdk:"conversations"`
	CreatedAt               types.String                           `tfsdk:"created_at"`
	CreatedBy               *NullableAuthorEntity                  `tfsdk:"created_by"`
	CurrentMilestone        types.String                           `tfsdk:"current_milestone"`
	CustomFields            []CustomFieldsFieldValue               `tfsdk:"custom_fields"`
	CustomerImpactSummary   types.String                           `tfsdk:"customer_impact_summary"`
	CustomersImpacted       types.Int32                            `tfsdk:"customers_impacted"`
	Description             types.String                           `tfsdk:"description"`
	DiscardedAt             types.String                           `tfsdk:"discarded_at"`
	Environments            []SuccinctEntity                       `tfsdk:"environments"`
	FieldRequirements       []IncidentEntityFieldRequirementEntity `tfsdk:"field_requirements"`
	Functionalities         []SuccinctEntity                       `tfsdk:"functionalities"`
	ID                      types.String                           `tfsdk:"id"`
	Impacts                 []IncidentsImpactEntity                `tfsdk:"impacts"`
	IncidentChannels        []IncidentsChannelEntity               `tfsdk:"incident_channels"`
	IncidentTickets         []TicketingTicketEntity                `tfsdk:"incident_tickets"`
	IncidentType            *NullableSuccinctEntity                `tfsdk:"incident_type"`
	IncidentURL             types.String                           `tfsdk:"incident_url"`
	Labels                  *NullableIncidentEntityLabels          `tfsdk:"labels"`
	LastNote                *NullableEventNoteEntity               `tfsdk:"last_note"`
	LastUpdate              types.String                           `tfsdk:"last_update"`
	LifecycleMeasurements   []IncidentsLifecycleMeasurementEntity  `tfsdk:"lifecycle_measurements"`
	LifecyclePhases         []IncidentsLifecyclePhaseEntity        `tfsdk:"lifecycle_phases"`
	Milestones              []IncidentsMilestoneEntity             `tfsdk:"milestones"`
	MonetaryImpact          types.Int32                            `tfsdk:"monetary_impact"`
	MonetaryImpactCents     types.Int32                            `tfsdk:"monetary_impact_cents"`
	Name                    types.String                           `tfsdk:"name"`
	Number                  types.Int32                            `tfsdk:"number"`
	Organization            *NullableOrganizationEntity            `tfsdk:"organization"`
	OrganizationID          types.String                           `tfsdk:"organization_id"`
	Priority                types.String                           `tfsdk:"priority"`
	PrivateID               types.String                           `tfsdk:"private_id"`
	PrivateStatusPageURL    types.String                           `tfsdk:"private_status_page_url"`
	ReportID                types.String                           `tfsdk:"report_id"`
	RetroExports            []NullableIncidentEntityRetroExport    `tfsdk:"retro_exports"`
	RoleAssignments         []IncidentsRoleAssignmentEntity        `tfsdk:"role_assignments"`
	Services                []SuccinctEntity                       `tfsdk:"services"`
	Severity                types.String                           `tfsdk:"severity"`
	SeverityColor           types.String                           `tfsdk:"severity_color"`
	SeverityCondition       types.String                           `tfsdk:"severity_condition"`
	SeverityConditionObject *NullableSeverityMatrixConditionEntity `tfsdk:"severity_condition_object"`
	SeverityImpact          types.String                           `tfsdk:"severity_impact"`
	SeverityImpactObject    *NullableSeverityMatrixImpactEntity    `tfsdk:"severity_impact_object"`
	StartedAt               types.String                           `tfsdk:"started_at"`
	StatusPages             []IncidentsStatusPageEntity            `tfsdk:"status_pages"`
	Summary                 types.String                           `tfsdk:"summary"`
	TagList                 []types.String                         `tfsdk:"tag_list"`
	TeamAssignments         []IncidentsTeamAssignmentEntityLite    `tfsdk:"team_assignments"`
	Ticket                  *NullableTicketingTicketEntity         `tfsdk:"ticket"`
}
