// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NullableRunbooksExecutionStepExecution struct {
	Data            *NullableRunbooksExecutionStepExecutionData `tfsdk:"data"`
	Error           types.String                                `tfsdk:"error"`
	PerformedAt     types.String                                `tfsdk:"performed_at"`
	PerformedBy     *NullableActor                              `tfsdk:"performed_by"`
	ScheduledFor    types.String                                `tfsdk:"scheduled_for"`
	State           types.String                                `tfsdk:"state"`
	WebhookDelivery *NullableRunbooksWebhookDelivery            `tfsdk:"webhook_delivery"`
}
