// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NullableRunbooksExecutionStepEntity struct {
	ActionSlug       types.String                                  `tfsdk:"action_slug"`
	ActionType       types.String                                  `tfsdk:"action_type"`
	Automatic        types.Bool                                    `tfsdk:"automatic"`
	ConferenceBridge *NullableIncidentsConferenceBridgeEntity      `tfsdk:"conference_bridge"`
	Config           *NullableRunbooksExecutionStepEntityConfig    `tfsdk:"config"`
	Executable       types.Bool                                    `tfsdk:"executable"`
	Execution        *NullableRunbooksExecutionStepExecutionEntity `tfsdk:"execution"`
	HasBeenRerun     types.Bool                                    `tfsdk:"has_been_rerun"`
	HasBeenRetried   types.Bool                                    `tfsdk:"has_been_retried"`
	ID               types.String                                  `tfsdk:"id"`
	IntegrationName  types.String                                  `tfsdk:"integration_name"`
	IntegrationSlug  types.String                                  `tfsdk:"integration_slug"`
	Name             types.String                                  `tfsdk:"name"`
	Repeatable       types.Bool                                    `tfsdk:"repeatable"`
	Repeats          types.Bool                                    `tfsdk:"repeats"`
	RepeatsAt        types.String                                  `tfsdk:"repeats_at"`
	RepeatsDuration  types.String                                  `tfsdk:"repeats_duration"`
	Rule             *NullableRulesRuleEntity                      `tfsdk:"rule"`
	StepElements     []StepElement                                 `tfsdk:"step_elements"`
}
