name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone SDK repo
        uses: actions/checkout@v3
        
      - name: Set up SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.FH_OPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_ed25519
          
      - name: Clone developers repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git clone git@github.com:firehydrant/developers.git /tmp/dev-repo
          cd /tmp/dev-repo
          git checkout main
          
      - name: Copy OpenAPI spec
        run: |
          cp /tmp/dev-repo/docs/public/openapi3_doc.json ${GITHUB_WORKSPACE}/openapi-raw.json

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          
      - name: Process OpenAPI spec
        run: |
          # Normalize the schema
          go run ./scripts/normalize openapi-raw.json openapi.json
          
          # Generate Terraform overlay
          go run ./scripts/overlay openapi.json ./scripts/overlay/manual-mappings.yaml
          
          # Move overlay to Speakeasy directory
          mkdir -p .speakeasy
          mv terraform-overlay.yaml .speakeasy/

      - name: Generate SDK
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          force: ${{ github.event.inputs.force }}
          mode: pr
          set_version: ${{ github.event.inputs.set_version }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}